### ISSUE TITLE
Question on supporting extensions

### ISSUE THREAD

**Issue by gabisurita** [ThinkAlexandria/diesel_geometry#1]
First, congratulations for this project! I've working for some time with diesel and postgres for radial distance computations using `Point` and the `earthdistance` module, but I hadn't time to isolate the API and publish a crate yet.

My question is if I should try to merge my work with `earthdistance` (or something that uses extensions, such as geom os gis) on this crate or try to publish it elsewhere using only the Point data type.

Thanks,

**Comment by YetAnotherMinion** [comment]
The design goal for this crate is to expose geometric types and operators that are builtin to databases  supported by diesel (Postgres, MySQL, MariaDB) so that geometric queries can be written using the diesel DSL.

This crate would then naturally be a building block for extension specific crates, such as PostGIS, or in your case earthdistance.

Our roadmap is to implement everything from postgres:
https://www.postgresql.org/docs/current/static/functions-geometry.html
https://www.postgresql.org/docs/current/static/datatype-geometric.html

If you have implementations of geometric functions, types, or operators, this crate would be a great home for them. I can work with you to merge them.

If you have earthdistance extension specific methods that you want to use in the DSL, I recommend creating a new crate such as `diesel_earthdistance` that then depends on this crate.

**Comment by Boscop** [comment]
@gabisurita I'm also interested in using `earthdistance` with diesel & PostGIS. 
Did you end up publishing your `earthdistance` functionality somewhere? :)
