### ISSUE TITLE
Add a working example

### ISSUE THREAD

**Issue by gabisurita** [ThinkAlexandria/diesel_geometry#2]
I know there are a few [good examples as tests](
https://github.com/ThinkAlexandria/diesel_geometry/blob/master/src/pg/types/geometric.rs#L148), but it would be good if they were available on the README or the first page of the docs.

The usage is pretty straightforward besides having to include the `Point` type on the `table!` macro. I had some hard time having to figure out this on the first time working with custom diesel types.

**Comment by YetAnotherMinion** [comment]
@gabisurita I agree that the rustdoc homepage for this crate is very unfriendly. It not obvious what the public API is or where to look for the type definitions unless you are very familiar with internal layout of the diesel crate.

The module documentation for each type does have working examples, but to realistically find it someone would have to use the search function, because its location is non-obvious:

https://docs.rs/diesel_geometry/1.2.1/diesel_geometry/pg/types/sql_types/struct.Point.html
https://docs.rs/diesel_geometry/1.2.1/diesel_geometry/pg/types/sql_types/struct.Box.html

I'll give the documentation a polish today. Originally this crate was internal only with the authors being the only users.

**Comment by YetAnotherMinion** [comment]
I released a new version with improved documentation. The issues around including the sq types in the `table!` are now directly addressed on the home page of docs.

https://docs.rs/diesel_geometry/1.2.2/diesel_geometry/
